{% set name = "libsimdpp" %}
{% set version = "2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/p12tic/libsimdpp.git
  git_rev: v{{ version }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja

about:
  home: http://p12tic.github.io/libsimdpp/doc/html/
  dev_url: https://github.com/hail-is/hail
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  license_family: BSL
  summary: |
    Hail is Python-based data analysis tool for working with genomic data.
  description: |
    libsimdpp is a header-only zero-overhead C++ wrapper around SIMD intrinsics. It supports multiple instruction sets
    via single interface. The same source code may be compiled for different instruction sets and linked to the same
    resulting binary. The library provides a convenient dynamic dispatch mechanism to select the fastest version of a
    function for the target processor.
  doc_url: http://p12tic.github.io/libsimdpp/doc/html/
  dev_url: https://github.com/p12tic/libsimdpp