
:: The environment variables 'LIBSIMDPP_NAME_VERSION' is
:: being passed through. If you are splitting build and test phases, 
:: ensure that this value is also set similarly at test time.
echo on

if not exist %PREFIX%\Library\lib\pkgconfig\%LIBSIMDPP_NAME_VERSION%.pc exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\capabilities.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\align.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\aligned_allocator.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\bit_and.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\bit_andnot.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\bit_not.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\bit_or.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\bit_xor.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\blend.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\cache.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\cast.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\cmp_eq.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\cmp_ge.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\cmp_gt.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\cmp_le.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\cmp_lt.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\cmp_neq.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\combine.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\detail\get_expr_bitwise.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\detail\get_expr_uint.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\detail\scalar_arg_impl.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\detail\subvec_extract.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\detail\subvec_insert.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\extract.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\extract_bits.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_abs.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_add.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_ceil.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_div.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_floor.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_fmadd.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_fmsub.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_isnan.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_isnan2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_max.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_min.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_mul.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_neg.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_rcp_e.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_rcp_rh.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_reduce_add.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_reduce_max.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_reduce_min.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_reduce_mul.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_rsqrt_e.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_rsqrt_rh.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_sign.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_sqrt.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_sub.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\f_trunc.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\for_each.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_abs.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_add.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_add_sat.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_avg.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_avg_trunc.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_div_p.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_max.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_min.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_mul.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_mull.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_neg.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_popcnt.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_reduce_add.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_reduce_and.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_reduce_max.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_reduce_min.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_reduce_mul.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_reduce_or.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_reduce_popcnt.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_shift_l.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_shift_r.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_sub.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\i_sub_sat.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\insert.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\load.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\load_packed2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\load_packed3.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\load_packed4.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\load_splat.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\load_u.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\make_float.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\make_int.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\make_shuffle_bytes_mask.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\make_uint.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\move_l.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\move_r.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\permute2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\permute4.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\permute_bytes16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\permute_zbytes16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\set_splat.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\shuffle1.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\shuffle2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\shuffle2x2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\shuffle4x2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\shuffle_bytes16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\shuffle_zbytes16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\splat.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\splat_n.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\split.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\store.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\store_first.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\store_last.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\store_masked.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\store_packed2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\store_packed3.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\store_packed4.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\store_u.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\stream.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\test_bits.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\to_float32.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\to_float64.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\to_int16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\to_int32.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\to_int64.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\to_int8.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\to_mask.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\transpose.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\unzip_hi.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\unzip_lo.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\zip_hi.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\core\zip_lo.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\deprecations.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\align.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\align_v128.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\altivec\load1.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\array.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\cast.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\cast.inl exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\cast_bitwise.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\construct_eval.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\eval_scalar.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\bit_and.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\bit_andnot.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\bit_not.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\bit_or.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\blend.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\f_abs.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\f_add.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\f_fmadd.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\f_fmsub.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\f_mul.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\f_neg.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\f_sub.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\i_abs.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\i_add.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\i_add_sat.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\i_mul.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\i_mull.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\i_neg.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\i_sub.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\i_sub_sat.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\scalar.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\splat_n.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\test_bits.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\expr\vec.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\extract128.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\for_each.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\get_expr.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\align.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\bit_and.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\bit_andnot.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\bit_not.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\bit_or.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\bit_xor.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\blend.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\cmp_eq.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\cmp_ge.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\cmp_gt.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\cmp_le.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\cmp_lt.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\cmp_neq.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\combine.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\conv_any_to_float32.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\conv_any_to_float64.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\conv_extend_to_int16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\conv_extend_to_int32.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\conv_extend_to_int64.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\conv_float_to_int16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\conv_float_to_int32.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\conv_float_to_int64.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\conv_float_to_int8.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\conv_shrink_to_int16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\conv_shrink_to_int32.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\conv_shrink_to_int8.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\conv_to_mask.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\conv_to_mask.inl exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\extract.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\extract_bits.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_abs.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_add.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_ceil.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_div.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_floor.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_fmadd.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_fmsub.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_isnan.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_isnan2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_max.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_min.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_mul.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_neg.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_rcp_e.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_rcp_rh.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_reduce_add.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_reduce_max.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_reduce_min.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_reduce_mul.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_rsqrt_e.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_rsqrt_rh.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_sign.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_sqrt.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_sub.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\f_trunc.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_abs.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_add.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_add_sat.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_avg.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_avg_trunc.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_max.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_min.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_mul_hi.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_mul_lo.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_mull.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_neg.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_popcnt.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_reduce_add.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_reduce_and.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_reduce_max.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_reduce_min.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_reduce_mul.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_reduce_or.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_reduce_popcnt.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_shift.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_shift_l.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_shift_l_v.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_shift_r.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_shift_r_v.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_sub.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\i_sub_sat.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\insert.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\load.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\load_packed2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\load_packed3.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\load_packed4.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\load_splat.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\load_u.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\make_const.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\mem_pack.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\mem_unpack.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\move_l.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\move_r.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\permute2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\permute4.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\permute_bytes16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\permute_zbytes16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\set_splat.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\shuffle128.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\shuffle2x2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\shuffle4x2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\shuffle_bytes16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\shuffle_emul.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\shuffle_zbytes16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\splat.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\splat_n.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\split.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\store.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\store_first.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\store_last.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\store_masked.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\store_packed2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\store_packed3.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\store_packed4.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\store_u.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\stream.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\test_bits.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\transpose.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\unzip_hi.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\unzip_lo.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\zip128.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\zip_hi.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn\zip_lo.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\insn_id.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\mem_block.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\neon\math_int.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\neon\memory_store.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\neon\shuffle.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\not_implemented.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\null\bitwise.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\null\compare.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\null\mask.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\null\math.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\null\memory.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\null\set.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\null\shuffle.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\null\transpose.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\preprocess_single_arch.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\preprocessor.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\shuffle\neon_int16x8.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\shuffle\neon_int32x4.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\shuffle\neon_int64x2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\shuffle\shuffle_mask.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\shuffle\sse_float32_4x2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\shuffle\sse_float64_4x2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\shuffle\sse_int32_4x2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\shuffle\sse_int64_4x2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\traits.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\vector_array_conv_macros.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\vector_array_macros.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\width.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\detail\workarounds.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\dispatch\arch.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\dispatch\collect_macros_generated.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\dispatch\dispatcher.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\dispatch\get_arch_gcc_builtin_cpu_supports.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\dispatch\get_arch_linux_cpuinfo.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\dispatch\get_arch_raw_cpuid.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\dispatch\get_arch_string_list.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\dispatch\macros_generated.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\dispatch\make_dispatcher.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\dispatch\preprocess_single_compile_arch.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\expr.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\expr.inl exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\bit_and.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\bit_not.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\bit_or.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\bit_xor.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\cmp_eq.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\cmp_ge.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\cmp_gt.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\cmp_le.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\cmp_lt.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\cmp_neq.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\f_add.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\f_div.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\f_mul.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\f_sub.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\i_add.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\i_mul.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\i_shift_l.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\i_shift_r.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\operators\i_sub.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\setup_arch.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\simd.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\this_compile_arch.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\any.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\empty_expr.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\float32.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\float32x16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\float32x4.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\float32x8.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\float64.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\float64x2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\float64x4.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\float64x8.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\fwd.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\generic.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int16x16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int16x32.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int16x8.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int32.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int32x16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int32x4.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int32x8.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int64.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int64x2.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int64x4.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int64x8.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int8.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int8x16.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int8x32.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\int8x64.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\tag.h exit 1
if not exist %PREFIX%\Library\include\libsimdpp-2.1\simdpp\types\traits.h exit 1