
# The environment variable 'LIBSIMDPP_NAME_VERSION' is 
# being passed through. If you are splitting build and test phases, 
# ensure that this value is also set similarly at test time.

test -e $PREFIX/lib/pkgconfig/$LIBSIMDPP_NAME_VERSION.pc
test -e $PREFIX/include/libsimdpp-2.1/simdpp/capabilities.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/align.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/aligned_allocator.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/bit_and.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/bit_andnot.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/bit_not.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/bit_or.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/bit_xor.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/blend.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/cache.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/cast.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/cmp_eq.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/cmp_ge.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/cmp_gt.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/cmp_le.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/cmp_lt.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/cmp_neq.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/combine.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/detail/get_expr_bitwise.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/detail/get_expr_uint.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/detail/scalar_arg_impl.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/detail/subvec_extract.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/detail/subvec_insert.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/extract.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/extract_bits.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_abs.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_add.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_ceil.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_div.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_floor.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_fmadd.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_fmsub.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_isnan.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_isnan2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_max.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_min.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_mul.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_neg.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_rcp_e.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_rcp_rh.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_reduce_add.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_reduce_max.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_reduce_min.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_reduce_mul.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_rsqrt_e.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_rsqrt_rh.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_sign.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_sqrt.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_sub.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/f_trunc.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/for_each.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_abs.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_add.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_add_sat.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_avg.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_avg_trunc.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_div_p.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_max.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_min.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_mul.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_mull.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_neg.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_popcnt.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_reduce_add.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_reduce_and.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_reduce_max.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_reduce_min.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_reduce_mul.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_reduce_or.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_reduce_popcnt.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_shift_l.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_shift_r.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_sub.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/i_sub_sat.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/insert.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/load.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/load_packed2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/load_packed3.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/load_packed4.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/load_splat.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/load_u.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/make_float.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/make_int.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/make_shuffle_bytes_mask.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/make_uint.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/move_l.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/move_r.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/permute2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/permute4.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/permute_bytes16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/permute_zbytes16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/set_splat.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/shuffle1.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/shuffle2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/shuffle2x2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/shuffle4x2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/shuffle_bytes16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/shuffle_zbytes16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/splat.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/splat_n.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/split.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/store.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/store_first.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/store_last.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/store_masked.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/store_packed2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/store_packed3.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/store_packed4.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/store_u.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/stream.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/test_bits.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/to_float32.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/to_float64.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/to_int16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/to_int32.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/to_int64.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/to_int8.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/to_mask.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/transpose.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/unzip_hi.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/unzip_lo.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/zip_hi.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/core/zip_lo.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/deprecations.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/align.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/align_v128.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/altivec/load1.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/array.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/cast.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/cast.inl
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/cast_bitwise.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/construct_eval.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/eval_scalar.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/bit_and.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/bit_andnot.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/bit_not.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/bit_or.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/blend.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/f_abs.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/f_add.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/f_fmadd.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/f_fmsub.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/f_mul.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/f_neg.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/f_sub.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/i_abs.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/i_add.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/i_add_sat.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/i_mul.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/i_mull.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/i_neg.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/i_sub.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/i_sub_sat.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/scalar.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/splat_n.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/test_bits.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/expr/vec.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/extract128.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/for_each.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/get_expr.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/align.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/bit_and.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/bit_andnot.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/bit_not.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/bit_or.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/bit_xor.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/blend.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/cmp_eq.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/cmp_ge.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/cmp_gt.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/cmp_le.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/cmp_lt.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/cmp_neq.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/combine.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/conv_any_to_float32.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/conv_any_to_float64.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/conv_extend_to_int16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/conv_extend_to_int32.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/conv_extend_to_int64.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/conv_float_to_int16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/conv_float_to_int32.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/conv_float_to_int64.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/conv_float_to_int8.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/conv_shrink_to_int16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/conv_shrink_to_int32.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/conv_shrink_to_int8.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/conv_to_mask.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/conv_to_mask.inl
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/extract.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/extract_bits.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_abs.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_add.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_ceil.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_div.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_floor.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_fmadd.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_fmsub.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_isnan.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_isnan2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_max.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_min.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_mul.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_neg.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_rcp_e.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_rcp_rh.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_reduce_add.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_reduce_max.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_reduce_min.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_reduce_mul.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_rsqrt_e.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_rsqrt_rh.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_sign.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_sqrt.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_sub.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/f_trunc.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_abs.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_add.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_add_sat.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_avg.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_avg_trunc.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_max.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_min.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_mul_hi.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_mul_lo.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_mull.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_neg.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_popcnt.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_reduce_add.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_reduce_and.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_reduce_max.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_reduce_min.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_reduce_mul.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_reduce_or.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_reduce_popcnt.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_shift.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_shift_l.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_shift_l_v.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_shift_r.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_shift_r_v.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_sub.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/i_sub_sat.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/insert.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/load.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/load_packed2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/load_packed3.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/load_packed4.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/load_splat.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/load_u.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/make_const.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/mem_pack.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/mem_unpack.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/move_l.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/move_r.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/permute2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/permute4.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/permute_bytes16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/permute_zbytes16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/set_splat.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/shuffle128.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/shuffle2x2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/shuffle4x2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/shuffle_bytes16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/shuffle_emul.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/shuffle_zbytes16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/splat.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/splat_n.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/split.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/store.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/store_first.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/store_last.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/store_masked.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/store_packed2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/store_packed3.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/store_packed4.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/store_u.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/stream.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/test_bits.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/transpose.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/unzip_hi.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/unzip_lo.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/zip128.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/zip_hi.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn/zip_lo.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/insn_id.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/mem_block.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/neon/math_int.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/neon/memory_store.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/neon/shuffle.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/not_implemented.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/null/bitwise.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/null/compare.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/null/mask.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/null/math.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/null/memory.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/null/set.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/null/shuffle.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/null/transpose.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/preprocess_single_arch.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/preprocessor.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/shuffle/neon_int16x8.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/shuffle/neon_int32x4.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/shuffle/neon_int64x2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/shuffle/shuffle_mask.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/shuffle/sse_float32_4x2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/shuffle/sse_float64_4x2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/shuffle/sse_int32_4x2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/shuffle/sse_int64_4x2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/traits.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/vector_array_conv_macros.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/vector_array_macros.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/width.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/detail/workarounds.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/dispatch/arch.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/dispatch/collect_macros_generated.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/dispatch/dispatcher.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/dispatch/get_arch_gcc_builtin_cpu_supports.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/dispatch/get_arch_linux_cpuinfo.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/dispatch/get_arch_raw_cpuid.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/dispatch/get_arch_string_list.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/dispatch/macros_generated.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/dispatch/make_dispatcher.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/dispatch/preprocess_single_compile_arch.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/expr.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/expr.inl
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/bit_and.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/bit_not.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/bit_or.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/bit_xor.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/cmp_eq.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/cmp_ge.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/cmp_gt.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/cmp_le.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/cmp_lt.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/cmp_neq.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/f_add.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/f_div.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/f_mul.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/f_sub.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/i_add.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/i_mul.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/i_shift_l.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/i_shift_r.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/operators/i_sub.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/setup_arch.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/simd.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/this_compile_arch.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/any.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/empty_expr.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/float32.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/float32x16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/float32x4.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/float32x8.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/float64.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/float64x2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/float64x4.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/float64x8.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/fwd.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/generic.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int16x16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int16x32.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int16x8.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int32.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int32x16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int32x4.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int32x8.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int64.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int64x2.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int64x4.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int64x8.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int8.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int8x16.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int8x32.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/int8x64.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/tag.h
test -e $PREFIX/include/libsimdpp-2.1/simdpp/types/traits.h